# site settings
title: GrokSwap
subtitle:
email: info@grokswap.com
description:
baseurl: ''
url: https://grokswap.com
author:
street_address:
city:
state:
zip_code:
country:
phone:

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 5

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url: https://instagram.com/grokswap
linkedin_url:
pinterest_url:
slack_url:
twitter_url: https://twitter.com/grokswap

# build settings
markdown: kramdown

sass:
  style: compressed

environment: production
google_analytics: G-EYJ3DVKQJ6